spring.application.name=weather-app

spring.mongodb.uri=mongodb://localhost:27017/weatherdb

weather.api.key=${API_KEY}
weather.api.base-url=https://api.openweathermap.org/data/2.5

server.port=8080



